### ISSUE TITLE
Easy False Swipe tutor option doesn't work

### ISSUE THREAD

**Issue by samwisethetired** [ProjectRevoTPP/pokeemerald-speedchoice#3]
**Describe the bug**
When trying to learn False Swipe from the tutor after the Easy False Swipe Tutor option is selected, the screen starts flashing random colours and the game softlocks.

**To Reproduce**
- Open up the ROM in mGBA, leave the speedchoice options as vanilla but set Easy False Swipe to Tutor. (Random name was Tanja)
- Progress through the game until the Swagger Tutor. I did this by using Mudkip, fighting all the trainers on the way to Roxanne, completing the story to get the PokeNav, fighting the rival and then travelling to Dewford by boat, making a beeline for stephen without fighting anything to hand over the letter, and then sailing to Slateport avoiding all trainers and then going straight to the Pokemon Fan Club house.
- Speak to the swagger tutor. He will offer to teach False Swipe, but the game will crash when a pokemon is selected to learn the move.

**Expected behavior**
False swipe should be taught to the selected pokemon, and the game shouldn't crash.

**Video of the bug**
https://user-images.githubusercontent.com/3778794/126015941-fb675497-924d-4c02-a6bb-e851a1a63134.mp4

**Details**
- Speedchoice version: 1.2.1, also tried 1.1.9 and it didn't seem to work there either.
- Emulator + version: mGBA 0.9.1
- Randomized? Tried with both randomized and un-randomized versions, different effects happened in the randomized version which may indicate memory mapping issues.

**Additional context**
Tried a number of different settings, two different versions of the game and both randomised and unrandomized versions.

**Comment by samwisethetired** [comment]
I have since tried following the same reproduction process using pokeemerald-ex-speedchoice-0.2.6 and the False Swipe move tutor works in that version.

**Comment by RevoSucks** [comment]
Works in latest version.

**Comment by samwisethetired** [comment]
What's the latest version? I just tried compiling from source and it still doesn't work. Or is this repo now effectively archived in favour of emerald-ex?
