### ISSUE TITLE
Evolve every level is low entropy

### ISSUE THREAD

**Issue by PikalaxALT** [ProjectRevoTPP/pokeemerald-speedchoice#5]
**Describe the bug**
RNG gets stuck in species loops when evolve-every-level is set.

**To Reproduce**
1. Be Shen, Adef, Chrism, and Keiz
2. Waltz onto the GDQ stage
3. Make the biggest mistake of GDQ history

**Expected behavior**
Evolutions are unpredictable and devoid of loops

**Screenshots**
N/A

**Details**
- Speedchoice version: 1.2.1
- Emulator + version: Console
- Randomized? Yes

**Additional context**
Fuck you Kirby keizaChu

**Comment by Louisvh** [comment]
This sounds like a joke report, but it's an actual issue: the way the evolution randomisation currently works, it's quite common for small loops to appear. I've just hit a loop of 1, i.e., a Pokémon that only evolves into itself. That kind of takes the fun out of a run.

--

I've done a little bit of browsing in the code, and from the face of it, it's not obvious why this would happen. The offending line is clearly [this one](https://github.com/ProjectRevoTPP/pokeemerald-speedchoice/blob/ba8f897094cc1ad7aebbdac7b810289185dbf0c9/src/pokemon.c#L5411) - I think the u32-to-u16 cast is the problem. That said, I don't quite understand why the seed is being re-set in the first place. There might be a randomness-related quirk I'm not aware of, but it seems superfluous.

**Comment by RevoSucks** [comment]
> This sounds like a joke report, but it's an actual issue: the way the evolution randomisation currently works, it's quite common for small loops to appear. I've just hit a loop of 1, i.e., a Pokémon that only evolves into itself. That kind of takes the fun out of a run.
> 
> --
> 
> I've done a little bit of browsing in the code, and from the face of it, it's not obvious why this would happen. The offending line is clearly [this one](https://github.com/ProjectRevoTPP/pokeemerald-speedchoice/blob/ba8f897094cc1ad7aebbdac7b810289185dbf0c9/src/pokemon.c#L5411) - I think the u32-to-u16 cast is the problem. That said, I don't quite understand why the seed is being re-set in the first place. There might be a randomness-related quirk I'm not aware of, but it seems superfluous.

This is not an issue. v1.2.3 updated the randomization, your code is outdated.

**Comment by Louisvh** [comment]
Ah fair enough. When I cloned it yesterday, the repo was still on v1.2.2, but good to see you'd already fixed it in your personal copy.

That said: why are you still re-generating a seed every time though? Why not just query Random(), optionally with the not-same-mon check from 1.2.3?

**Comment by RevoSucks** [comment]
Because then you can just reset and re-roll for the evo species you want. In order for it to qualify, the same pokemon species+personality+level needs to result in the same "next species" to evolve into.

I'm not changing this approach. Go somewhere else.

**Comment by Louisvh** [comment]
That's fair; I'm not actually suggesting you change it. It just seemed overengineered to me, but I didn't think of reset-persistence.

I'm pretty sure "wont fix" is an incorrect label though; the loops were happening because the level information was being clipped out of the seed due to the 32-to-16 cast, resulting in the same seed for the same mon regardless of level. With the new implementation, that cannot happen. Sounds like fixed to me.
