### ISSUE TITLE
Cannot link to Pokemon XD

### ISSUE THREAD

**Issue by DarthPidgey** [ProjectRevoTPP/pokeemerald-speedchoice#7]
**Describe the bug**
Trying to link to Pokemon XD to trade gives an error on the GBA screen "This Game Pak cannot link to Pokemon XD" The same save on a vanilla emerald links successfully. The same speedchoice file can also link to Pokemon Colosseum, Pokemon Box without issues.

**To Reproduce**
Try to link Emerald Speedchoice to Pokemon XD trade menu

**Expected behavior**
To be able to trade between Pokemon XD and Emerald Speedchoice

**Details**
- Speedchoice version: 1.2.3 from Shen's discord
- Emulator + version: Real GBA and GCN hardware with an official GBA GCN Link Cable
- Randomized? No

**Additional context**

**Comment by DarthPidgey** [comment]
I've found a workaround, changing the Speedchoice rom header to a Vanilla Emerald rom header via a Hex editor lets Speedchoice successfully trade with XD. I guess XD has a header check compared to Colosseum and Box and this behavior seems to be undocumented as the only requirements are a hall of fame check according to this  https://gist.github.com/Deokishisu/c9abef7d41dbd898194197c2509c62fd

**Comment by RevoSucks** [comment]
Supporting linking is out of scope.
